### ISSUE TITLE
Feature Request: Support for failed jobs and jobs priority

### ISSUE THREAD

**Issue by altafhussain10** [renatocason/magento2-module-mq#6] opened 2018-08-16 06:13 UTC
Hi @renatocason and @grafikchaos ,

I started to use your module with superviosr process manager to run the queues all the time and it works like a charm. I would like to suggest two features whcih can increase this module capabilities more. 

1. Failed Jobs. This can be a useful feature. Once a job throws an exception, the job information and the exception can be stored in a table like **ce_failed_queue_message** . Also, failed jobs can be added to queue again.

2. Jobs Prirotiy: Some time we have high priority jobs like sending notifications and some low priority jobs like a long running script updating some data. I think it will be great to have a priority setup in this module so that high priority jobs can be executed first. 

I hope I will see some feedback from you regarding this. 

Thank you

**Comment by renatocason** [comment] 2018-08-19 12:35
Hi @altafhussain10 ,

Thanks for the feedback, glad to hear it's working fine for you!
Some questions regarding your points:
1. Is there a specific reason why you would prefer a database table rather than using the PSR logger? That would add more flexibility, as in normal cases you might just leave it as-is, but for more advanced scenarios you could add additional monolog handlers via dependency injection
2. With this do you mean that you might have different queues with different priorities, or that in the same queue you might have messages with different priorities?

Thanks,
Renato

**Comment by eross1lf** [comment] 2018-09-03 07:15
Hi Renato

Thanks for the module. It works great.
Re-queueing failed jobs worked in the previous version. This has now changed in StartConsumerCommand.php where the flag is set to false at the reject call: $broker->reject($message, false); 
Maybe the flag should be configuration based?

Thanks,
Laszlo

**Comment by renatocason** [comment] 2018-09-04 10:05
Hi @eross1lf ,

Thanks for the feedback, definitely worth adding an option to the consumer command.
I'm sorry there was a change of behaviour on the update, unfortunately that was caused by the fact that _requeue_ was defaulted to false in the interface and to true in the implementation.
The option on the command should fix that, will proceed in the next days with that.

Thanks,
Renato

**Comment by renatocason** [comment] 2018-09-04 22:10
Hi @eross1lf ,

I just created a new release 1.0.1 that supports the requeue option in the command.
Let me know if that works fine for you!

Thanks,
Renato

**Comment by eross1lf** [comment] 2018-09-05 20:48
Hi @renatocason 

It works great. Now the option of re-queueing is covered.
Thanks again for shearing this module!

Thanks & Regards,
Laszlo

**Comment by renatocason** [comment] 2018-09-06 09:27
Thanks for the feedback, @eross1lf!
I'm closing the issue due to no feedback to my questions @altafhussain10, but feel free to reopen it if you have the time to reply.

Regards,
Renato

**Closed as completed by renatocason** 2018-09-06 09:27 UTC
